name: github-action-svu
author: charlesthomas
description: use https://github.com/caarlos0/svu to calculate the next semantic version for your repo by reading the commit log
inputs:
  # GHA-specific inputs (not passed to svu)
  cmd:
    description: |-
      svu sub-command
      options:
        next: prints the next version based on the git log
        current: prints current version
        major: new major version
        minor: new minor version
        patch: new patch version
        prerelease: new pre release version based on the next version calculated from git log
      this github action will always run current and provide its value as an output.
      if cmd is set to current, that is all it will do.
      in all other cases, the specified sub-command will also be run and output as "next."
    required: false
    default: "next"
  clone:
    description: |-
      git clone the repo before running svu
      unnecessary if you use actions/checkout ahead of this in your workflow
    required: false
    default: false
  unshallow:
    description: |-
      run `git fetch --unshallow` before running `svu`
      useful if you use actions/checkout ahead of this in your workflow with the default depth
      ignored if clone is true
    required: false
    default: false
  pushTag:
    description: |-
      run `git tag $next && git push --tags` where `$next` is the value calculated by svu
      if the calulated new version and `svu current` are the same, nothing is pushed
  # svu 3.0 global inputs
  tagMode:
    description: |-
      svu --tag.mode flag
      determine if it should look for tags in all branches, or just the current one
      THIS INPUTS DEFAULT DIFFERS FROM svu DEFAULT
      In order to preserve reverse-compatibility with this github action, the default INPUT is "current".
      In svu v3, the FLAG default is "all"
    required: false
    default: "current"
  tagPattern:
    description: |-
      svu --tag.pattern flag
      ignore tags that do not match the given pattern
    required: false
  tagPrefix:
    description: |-
      svu --tag.prefix flag
      sets a tag custom prefix (default "v")
    required: false
    default: "v"
  verbose:
    description: |-
      svu --verbose flag
      enable logs
    required: false
    default: false
  # svu 3.0 next inputs
  always:
    description: |-
      svu next --always flag
      if no commits trigger a version change, increment the patch
    required: false
    default: false
  logDirectory:
    description: |-
      svu next --log.directory flag
      only use commits that changed files in the given directories
    required: false
  metadata:
    description: |-
      svu next --metadata flag
      sets the version metadata
    required: false
  prerelease:
    description: |-
      svu prerelease --prerelease or svu next --prelease flag
      sets the version prerelease
    required: false
  v0:
    description: |-
      svu next --v0 flag
      prevent major version increments if current version is still v0
    required: false
    default: false
  # legacy inputs
  pattern:
    description: |-
      --pattern=PATTERN svu flag
      "LEGACY! Use tagPattern instead."
    required: false
  prefix:
    description: |-
      --prefix svu flag
      LEGACY! Use tagPrefix instead
    required: false
  build:
    description: |-
      --build=BUILD svu flag
      LEGACY! Use metadata instead
    required: false
  directory:
    description: |-
      --directory svu flag
      LEGACY! Use logDirectory instead
    required: false
  forcePatchIncrement:
    description: |-
      LEGACY! Use always instead
    required: false
    default: false
outputs:
  current:
    description: |-
      the output of `svu current` before running `svu $cmd`, eg `svu next`
  next:
    description: |-
      the next version, if any cmd other than `current` was used
      eg `svu next`, `svu prerelease`, `svu major`, etc
  changed:
    description: |-
      whether the next version calculated by `svu $cmd` matches `svu current`
      useful if you use `svu next` without `--force-patch-increment`
      and push the tag yourself outside of this step
runs:
  using: docker
  image: docker://ghcr.io/charlesthomas/github-action-svu:v1.1.0-3.1.0
