#!/bin/bash
set -ex

# /github/workspace is where github actions always mounts the repo
# it can't be changed, and this is required to prevent svu from throwing errors
git config --global --add safe.directory /github/workspace

if [[ "${INPUT_FETCHTAGS}" == "true" ]]; then
    git fetch --unshallow
else
    git clone https://github.com/${GITHUB_REPOSITORY} .
fi

CURRENT=$(/bin/svu current)
echo "current=${CURRENT}" >> "$GITHUB_OUTPUT"
if [[ "${INPUT_CMD}" == "current" ]]; then
    echo "next=${CURRENT}" >> "$GITHUB_OUTPUT"
    echo "changed=false" >> "$GITHUB_OUTPUT"
    exit 0
fi

ARGS=""
if [[ "${INPUT_PATTERN}" != "" ]]; then
    ARGS="${ARGS} --pattern=${INPUT_PATTERN}"
fi
if [[ "${INPUT_PREFIX}" != "" ]] && [[ "${INPUT_PREFIX}" != "v" ]]; then
    ARGS="${ARGS} --prefix=${INPUT_PREFIX}"
fi
if [[ "${INPUT_BUILD}" != "" ]]; then
    ARGS="${ARGS} --build=${INPUT_BUILD}"
fi
if [[ "${INPUT_DIRECTORY}" != "" ]]; then
    ARGS="${ARGS} --directory=${INPUT_DIRECTORY}"
fi
if [[ "${INPUT_TAGMODE}" != "" ]] && [[ "${INPUT_TAGMODE}" != "current-branch" ]]; then
    ARGS="${ARGS} --tag-mode=${INPUT_TAG-MODE}"
fi

if [[ "${INPUT_CMD}" == "next" ]] && [[ "${INPUT_FORCEPATCHINCREMENT}" == "true" ]]; then
    ARGS="${ARGS} --force-patch-increment"
fi
if [[ "${INPUT_CMD}" == "prerelease" ]] && [[ "${INPUT_PRERELEASE}" == "" ]]; then
    ARGS="${ARGS} --pre-release=${INPUT_PRERELEASE}"
fi

NEXT=$(/bin/svu ${INPUT_CMD} ${ARGS})
echo "next=${NEXT}" >> "$GITHUB_OUTPUT"
if [[ "${NEXT}" == "${CURRENT}" ]]; then
    echo "changed=false" >> "$GITHUB_OUTPUT"
else
    echo "changed=true" >> "$GITHUB_OUTPUT"
    if [[ "${INPUT_PUSHTAGS}" == "true" ]]; then
        git tag "${NEXT}"
        git push --tags
    fi
fi
